#!/usr/bin/env node
/* Read the referenced artwork into the modules that need it — `make diagrams`,
   or `ARGS=--check` to ask whether they are still in step.

   Artwork is referenced rather than linked so its colours are the page's
   tokens, and the files then owe two things. The viewBox, since `<use>` carries
   the shapes and not the size and a drawing names a `<g>`, which carries none —
   kept by hand a viewBox drifts, and a drifted one is a drawing squashed by a
   fraction. And the markup, because a card opened from disk resolves a
   reference to nothing; only the static render path imports that, so `soul.js`
   never pays for it. */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { FRONTEND, ROOT } from './lib/cards.ts';
import * as report from './lib/report.ts';

const ASSETS = join(FRONTEND, 'assets');
const DIR = join(ASSETS, 'diagrams');

/** The group `<use>` points at in a drawing. Every one of them names it the
    same: pointing at the root `<svg>` would clone the `<title>` and `<desc>`
    into a wrapper that already carries the alt text, and read the drawing out
    twice. A mark has no `<title>` to clone and names its root instead, which
    is what lets the same file be opened on its own and used as a favicon. */
const GROUP = /<g id="soul-ref">([\s\S]*)<\/g>/;

/** A mark says it may be referenced by naming its root. */
const ROOTED = /<svg\b[^>]*\sid="soul-ref"/;

const viewBoxOf = (file: string, text: string): string => {
  const viewBox = /<svg[^>]*\sviewBox="([^"]+)"/.exec(text)?.[1];
  if (!viewBox) throw new Error(`${file}: no viewBox on the root <svg> — artwork without one cannot be referenced`);
  return viewBox;
};

/* A double dash inside a comment is illegal XML, and an SVG is parsed as XML
   the moment it is fetched, so the file renders nothing anywhere and the only
   sign of it is a blank space. Easy to write by accident, because the token
   names these files are full of are spelled with two: a note explaining
   `var(--token, #hex)` breaks the drawing it is explaining. */
const wellFormed = (file: string, text: string): void => {
  for (const comment of text.matchAll(/<!--([\s\S]*?)-->/g)) {
    if ((comment[1] ?? '').includes('--')) {
      throw new Error(`${file}: a comment carries a double dash — that is malformed XML, and the file draws nothing wherever it is fetched`);
    }
  }
};

const drawings = readdirSync(DIR)
  .filter((f) => f.endsWith('.svg'))
  .sort()
  .map((file) => {
    const text = readFileSync(join(DIR, file), 'utf8');
    wellFormed(file, text);
    const viewBox = viewBoxOf(file, text);
    const shapes = GROUP.exec(text)?.[1];
    if (!shapes) throw new Error(`${file}: no <g id="soul-ref"> — the drawing has nothing <use> can reach`);
    return { name: file.replace(/\.svg$/, ''), viewBox, shapes: shapes.trim() };
  });

/* A mark goes into the card whole, as a nested `<svg>` rather than loose
   shapes: that is what carries the coordinate system across, since the wrapper
   states a size and no viewBox. What comes out is the drawing and nothing else
   — the wrapper already says what the picture is, and the `id` goes too, or a
   card showing one mark twice ships it twice. */
const CARRIED = [
  [/<\?xml[^>]*\?>\s*/g, ''],
  [/\s*<!--[\s\S]*?-->/g, ''],
  [/\s*<title>[\s\S]*?<\/title>/g, ''],
  [/\s+(?:id|role|aria-label)="[^"]*"/g, ''],
] as const;

const marks = readdirSync(ASSETS)
  .filter((f) => f.endsWith('.svg'))
  .sort()
  .map((file) => ({ file, text: readFileSync(join(ASSETS, file), 'utf8') }))
  .filter(({ text }) => ROOTED.test(text))
  .map(({ file, text }) => {
    wellFormed(file, text);
    viewBoxOf(file, text);
    return {
      name: file.replace(/\.svg$/, ''),
      svg: CARRIED.reduce((svg, [pattern, to]) => svg.replace(pattern, to), text).trim(),
    };
  });

const header = (what: string): string =>
  `/* GENERATED by scripts/diagrams.ts — from assets/. Do not edit.\n` +
  `   ${what}\n` +
  `   Redraw the file and run \`make diagrams\`. */\n\n`;

const MODULES: readonly (readonly [file: string, text: string])[] = [
  [
    'diagrams.generated.ts',
    header('The coordinate systems. Safe for the browser bundle.') +
      `/** The coordinate system each drawing is in, keyed by file name without\n` +
      `    the extension. \`sds-figure\` puts it on the wrapper it references the\n` +
      `    drawing from, because \`<use>\` does not bring a size across. */\n` +
      `export const DIAGRAM_VIEWBOX: Readonly<Record<string, string>> = {\n` +
      drawings.map((d) => `  ${JSON.stringify(d.name)}: ${JSON.stringify(d.viewBox)},`).join('\n') +
      `\n};\n`,
  ],
  [
    'diagrams.svg.generated.ts',
    header('The shapes. For the static export — never imported by src/index.ts.') +
      `export const DIAGRAM_SHAPES: Readonly<Record<string, string>> = {\n` +
      drawings.map((d) => `  ${JSON.stringify(d.name)}: ${JSON.stringify(d.shapes)},`).join('\n') +
      `\n};\n\n` +
      `/** The marks, whole — a nested \`<svg>\` carrying its own coordinate\n` +
      `    system, because the wrapper around a mark states a size and no\n` +
      `    viewBox. Keyed by file name without the extension. */\n` +
      `export const MARK_SVG: Readonly<Record<string, string>> = {\n` +
      marks.map((m) => `  ${JSON.stringify(m.name)}: ${JSON.stringify(m.svg)},`).join('\n') +
      `\n};\n`,
  ],
];

const check = process.argv.includes('--check');
const stale: string[] = [];

report.open('diagrams', check ? 'the modules match the drawings' : 'read the drawings into the modules');

for (const [file, text] of MODULES) {
  const out = join(FRONTEND, 'src', 'components', file);
  if (check) {
    if (readFileSync(out, 'utf8') !== text) stale.push(`src/components/${file} is out of date`);
  } else {
    writeFileSync(out, text);
    report.fact(`src/components/${file}`, 'written');
  }
}

if (!check) {
  for (const d of drawings) report.fact(d.name, d.viewBox);
  for (const m of marks) report.fact(m.name, 'referenced whole');
}
report.summary(`${drawings.length} drawings · ${marks.length} marks`, stale);
process.exit(stale.length ? 1 : 0);
