#!/usr/bin/env node
/* Read the drawings in assets/diagrams/ into the two modules that need them.

   A drawing is referenced into the page rather than linked as an image, so
   that its colours are the page's tokens — `src/lib/art.ts` says why. That
   costs two things the files themselves have to supply.

   **The viewBox.** `<use>` carries the shapes across and not the size, so the
   wrapper `<svg>` has to state the coordinate system — and the wrapper is
   written by a component that has never opened the file. A hand-kept list
   would drift the first time a drawing was recomposed, and a drifted viewBox
   is a drawing squashed by a fraction: visible, but not obviously a stale
   constant.

   **The markup.** A specimen card is opened from disk with no server, where a
   reference to another file resolves to nothing — the same reason
   `icon.static.ts` exists, and this is its counterpart for drawings. Only the
   static render path imports it, so the 40 kB never reaches `soul.js`.

     make diagrams
     make diagrams ARGS=--check    are the modules still in step
*/
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { ROOT } from './lib/cards.ts';

const DIR = join(ROOT, 'assets', 'diagrams');

/** The group `<use>` points at. Every drawing names it the same: pointing at
    the root `<svg>` would clone the `<title>` and `<desc>` into a wrapper
    that already carries the alt text, and read the drawing out twice. */
const GROUP = /<g id="art">([\s\S]*)<\/g>/;

const drawings = readdirSync(DIR)
  .filter((f) => f.endsWith('.svg'))
  .sort()
  .map((file) => {
    const text = readFileSync(join(DIR, file), 'utf8');
    const viewBox = /<svg[^>]*\sviewBox="([^"]+)"/.exec(text)?.[1];
    if (!viewBox) throw new Error(`${file}: no viewBox on the root <svg> — a drawing without one cannot be referenced`);
    const shapes = GROUP.exec(text)?.[1];
    if (!shapes) throw new Error(`${file}: no <g id="art"> — the drawing has nothing <use> can reach`);
    return { name: file.replace(/\.svg$/, ''), viewBox, shapes: shapes.trim() };
  });

const header = (what: string): string =>
  `/* GENERATED by scripts/diagrams.ts — from assets/diagrams/. Do not edit.\n` +
  `   ${what}\n` +
  `   Redraw the file and run \`make diagrams\`. */\n\n`;

const MODULES: readonly (readonly [file: string, text: string])[] = [
  [
    'diagrams.generated.ts',
    header('The coordinate systems. Safe for the browser bundle.') +
      `/** The coordinate system each drawing is in, keyed by file name without\n` +
      `    the extension. \`sds-figure\` puts it on the wrapper it references the\n` +
      `    drawing from, because \`<use>\` does not bring a size across. */\n` +
      `export const DIAGRAM_VIEWBOX: Readonly<Record<string, string>> = {\n` +
      drawings.map((d) => `  ${JSON.stringify(d.name)}: ${JSON.stringify(d.viewBox)},`).join('\n') +
      `\n};\n`,
  ],
  [
    'diagrams.svg.generated.ts',
    header('The shapes. For the static export — never imported by src/index.ts.') +
      `export const DIAGRAM_SHAPES: Readonly<Record<string, string>> = {\n` +
      drawings.map((d) => `  ${JSON.stringify(d.name)}: ${JSON.stringify(d.shapes)},`).join('\n') +
      `\n};\n`,
  ],
];

const check = process.argv.includes('--check');
let stale = 0;
for (const [file, text] of MODULES) {
  const out = join(ROOT, 'src', 'components', file);
  if (check) {
    if (readFileSync(out, 'utf8') !== text) {
      console.error(`✗ src/components/${file} is out of date — run \`make diagrams\``);
      stale++;
    }
  } else {
    writeFileSync(out, text);
    console.log(`src/components/${file}`);
  }
}

if (check) {
  if (stale) process.exit(1);
  console.log(`   ${drawings.length} drawings, in step`);
} else {
  for (const d of drawings) console.log(`${d.name} — ${d.viewBox}`);
}
