#!/usr/bin/env node
/* Materialise fonts/ from the @fontsource-variable packages.

   The brand faces are a dependency, not a checked-in binary: npm owns the
   version and `fonts/` is generated. It still has to be real files on disk,
   because a rendered design resolves `styles.css` and cannot reach into
   node_modules. Only the styles and subsets this system uses, and only woff2.
   Run by the container entrypoint whenever `fonts/` is missing.

     make fonts
*/
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { FRONTEND, ROOT } from './lib/cards.ts';

/* The faces the design system declares. A variable face covers every weight
   the tokens expose, so this list only chooses styles and subsets. */
const FAMILIES = [
  {
    pkg: '@fontsource-variable/source-sans-3',
    family: 'Source Sans 3',
    styles: ['normal', 'italic'],
  },
  {
    pkg: '@fontsource-variable/source-code-pro',
    family: 'Source Code Pro',
    styles: ['normal'],
  },
];
const SUBSETS = ['latin', 'latin-ext'];

const OUT = join(FRONTEND, 'fonts');
rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

const blocks = [];
let copied = 0;

for (const { pkg, family, styles } of FAMILIES) {
  const base = join(ROOT, 'node_modules', pkg);
  const slug = pkg.split('/')[1];
  for (const style of styles) {
    /* The complete stylesheet carries unicode-range; the per-subset files
       omit it. The ranges keep the browser from fetching both subsets. */
    const cssName = `wght${style === 'italic' ? '-italic' : ''}.css`;
    let css;
    try {
      css = readFileSync(join(base, cssName), 'utf8');
    } catch {
      throw new Error(`${pkg}/${cssName} is missing — does that style exist upstream?`);
    }
    for (const subset of SUBSETS) {
      const fileName = `${slug}-${subset}-wght-${style}.woff2`;
      const block = css
        .split('@font-face')
        .find((b) => b.includes(`/files/${fileName}`));
      if (!block) throw new Error(`${pkg}: no ${subset} face for ${style}`);
      const range = /unicode-range:\s*([^;]+);/.exec(block);

      copyFileSync(join(base, 'files', fileName), join(OUT, fileName));
      copied++;
      blocks.push(`@font-face {
  font-family: '${family}';
  font-style: ${style};
  font-weight: 200 900;
  font-display: optional;
  src: url('${fileName}') format('woff2');${range?.[1] ? `\n  unicode-range: ${range[1].trim()};` : ''}
}`);
    }
  }
  copyFileSync(join(base, 'LICENSE'), join(OUT, `LICENSE-${family.replace(/\s+/g, '')}.txt`));
}

const versions = FAMILIES.map(({ pkg }) => {
  const v = JSON.parse(readFileSync(join(ROOT, 'node_modules', pkg, 'package.json'), 'utf8')).version;
  return `     ${pkg}@${v}`;
}).join('\n');

writeFileSync(join(OUT, 'fonts.css'), `/* GENERATED by scripts/fonts.ts — do not edit.

   Source:
${versions}

   Both families are SIL Open Font License 1.1; the licence text ships
   beside this file. Latin and latin-ext, variable woff2 only. Regenerate with
   \`make fonts\` after changing the face list in the script. */

${blocks.join('\n\n')}
`);

console.log(`fonts/ — ${copied} woff2, ${blocks.length} @font-face rules, ${FAMILIES.length} licences`);
