#!/usr/bin/env node
/* Materialise fonts/ from the @fontsource packages.

   The brand faces are a dependency, not a checked-in binary: npm owns the
   version, and `fonts/` is generated. It still has to end up as real files
   on disk, because a rendered design resolves `styles.css` and its imports
   — it cannot reach into node_modules.

   Only the weights and subsets this system actually uses are copied, and
   only woff2: every browser that can run these designs supports it, and the
   .woff fallback would double the payload for nothing.

   Run by the container entrypoint whenever fonts/ is missing, so any
   container starts with a working tree.

     make fonts
*/
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { ROOT } from './lib/cards.ts';

/* The faces the design system declares. Adding a weight here is the only
   step needed to ship it — everything else follows. */
const FAMILIES = [
  {
    pkg: '@fontsource/source-sans-3',
    family: 'Source Sans 3',
    faces: [
      { weight: 200 }, { weight: 300 }, { weight: 400 },
      { weight: 400, italic: true }, { weight: 600 }, { weight: 700 },
    ],
  },
  {
    pkg: '@fontsource/source-code-pro',
    family: 'Source Code Pro',
    faces: [{ weight: 400 }, { weight: 500 }, { weight: 600 }],
  },
];
const SUBSETS = ['latin', 'latin-ext'];

const OUT = join(ROOT, 'fonts');
rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

const blocks = [];
let copied = 0;

for (const { pkg, family, faces } of FAMILIES) {
  const base = join(ROOT, 'node_modules', pkg);
  const slug = pkg.split('/')[1];
  for (const { weight, italic } of faces) {
    const style = italic ? 'italic' : 'normal';
    /* The per-weight stylesheet is the one that carries unicode-range: the
       per-subset files omit it, because importing one subset alone means
       applying it unconditionally. We ship several subsets side by side, so
       the ranges are what keep the browser from downloading all of them. */
    const cssName = `${weight}${italic ? '-italic' : ''}.css`;
    let css;
    try {
      css = readFileSync(join(base, cssName), 'utf8');
    } catch {
      throw new Error(`${pkg}/${cssName} is missing — does that weight exist upstream?`);
    }
    for (const subset of SUBSETS) {
      const fileName = `${slug}-${subset}-${weight}-${style}.woff2`;
      const block = css
        .split('@font-face')
        .find((b) => b.includes(`/files/${fileName}`));
      if (!block) throw new Error(`${pkg}: no ${subset} face for ${weight} ${style}`);
      const range = /unicode-range:\s*([^;]+);/.exec(block);

      copyFileSync(join(base, 'files', fileName), join(OUT, fileName));
      copied++;
      blocks.push(`@font-face {
  font-family: '${family}';
  font-style: ${style};
  font-weight: ${weight};
  font-display: swap;
  src: url('${fileName}') format('woff2');${range?.[1] ? `\n  unicode-range: ${range[1].trim()};` : ''}
}`);
    }
  }
  copyFileSync(join(base, 'LICENSE'), join(OUT, `LICENSE-${family.replace(/\s+/g, '')}.txt`));
}

const versions = FAMILIES.map(({ pkg }) => {
  const v = JSON.parse(readFileSync(join(ROOT, 'node_modules', pkg, 'package.json'), 'utf8')).version;
  return `     ${pkg}@${v}`;
}).join('\n');

writeFileSync(join(OUT, 'fonts.css'), `/* GENERATED by scripts/fonts.ts — do not edit.

   Source:
${versions}

   Both families are SIL Open Font License 1.1; the licence text ships
   beside this file. Latin and latin-ext, woff2 only. Regenerate with
   \`make fonts\` after changing the face list in the script. */

${blocks.join('\n\n')}
`);

console.log(`fonts/ — ${copied} woff2, ${blocks.length} @font-face rules, ${FAMILIES.length} licences`);
