#!/usr/bin/env node
/* Materialise assets/icons/ from the @typo3/icons package.

   The identifiers below are the core's own — the same strings
   `typo3_icon_lookup` returns — so design and runtime name the same thing, and
   taking them from the package makes drift impossible. A missing icon is
   contributed upstream, never drawn locally and never substituted, so this
   FAILS on a declared identifier the package does not have.

     make icons
*/
import { copyFileSync, cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { FRONTEND, ROOT } from './lib/cards.ts';
import * as report from './lib/report.ts';

/* Which categories this system ships. Everything else about an icon —
   whether it exists, where its file is, which sprite carries it, what a
   deprecated spelling resolves to — comes from the package's own manifest.
   Nothing here scans a directory or guesses a path from an identifier. */
const CATEGORIES = ['actions'] as const;

const PKG = join(ROOT, 'node_modules', '@typo3', 'icons');
const OUT = join(FRONTEND, 'assets', 'icons');

interface Manifest {
  icons: Record<string, { identifier: string; category: string; svg: string; sprite: string }>;
  aliases: Record<string, string>;
}

const manifest = JSON.parse(readFileSync(join(PKG, 'dist', 'icons.json'), 'utf8')) as Manifest;
const ICONS = Object.values(manifest.icons)
  .filter((i) => (CATEGORIES as readonly string[]).includes(i.category))
  .sort((a, b) => a.identifier.localeCompare(b.identifier));

const missing = ICONS.filter((i) => !existsSync(join(PKG, 'dist', i.svg)));
if (missing.length) {
  report.bad(`named by the manifest but not on disk: ${missing.map((i) => i.identifier).join(', ')}`);
  process.exit(1);
}

rmSync(OUT, { recursive: true, force: true });

/* The package's own layout, mirrored. Three shapes, none rebuilt here: a single
   file for whatever reaches for one, the sprite for a whole category, and the
   manifest as the lookup. The manifest's paths are relative to itself, so the
   files have to sit where it says — flattening them and keeping it verbatim
   would ship a lookup that resolves to nothing. */
mkdirSync(join(OUT, 'svgs'), { recursive: true });
mkdirSync(join(OUT, 'sprites'), { recursive: true });
for (const category of CATEGORIES) {
  cpSync(join(PKG, 'dist', 'svgs', category), join(OUT, 'svgs', category), { recursive: true });
  copyFileSync(join(PKG, 'dist', 'sprites', `${category}.svg`), join(OUT, 'sprites', `${category}.svg`));
}

/* Filtered to what is actually here. Copied verbatim it would name 404 icons
   this system does not ship — the same shape of lie as a stale token. */
const shipped = new Set(ICONS.map((i) => i.identifier));
writeFileSync(join(OUT, 'icons.json'), `${JSON.stringify({
  icons: Object.fromEntries(ICONS.map((i) => [i.identifier, i])),
  aliases: Object.fromEntries(Object.entries(manifest.aliases).filter(([, to]) => shipped.has(to))),
}, null, 0)}\n`);

copyFileSync(join(PKG, 'LICENSE'), join(OUT, 'LICENSE-TYPO3.Icons.txt'));

const version = JSON.parse(readFileSync(join(PKG, 'package.json'), 'utf8')).version;

/* Two generated modules, split by who may pay for them. `icons.generated.ts` is
   the identifiers and their type, small enough for the browser bundle, and
   `IconId` makes a misspelling a compile error rather than a throw at render
   time. `icons.svg.generated.ts` is every glyph as a string and must never
   reach the bundle, which splitting it keeps true by construction. */
const header = (what: string): string =>
  `/* GENERATED by scripts/icons.ts — @typo3/icons@${version}, MIT. Do not edit.\n` +
  `   ${what}\n` +
  `   Add a category to CATEGORIES in that script and run \`make icons\`. */\n\n`;

writeFileSync(
  join(FRONTEND, 'src', 'components', 'icons.generated.ts'),
  header('The identifiers. Safe for the browser bundle.') +
    `export type IconId =\n${ICONS.map((i) => `  | '${i.identifier}'`).join('\n')};\n\n` +
    `export const ICON_IDS: readonly IconId[] = [\n` +
    ICONS.map((i) => `  ${JSON.stringify(i.identifier)},`).join('\n') +
    `\n];\n`,
);

writeFileSync(
  join(FRONTEND, 'src', 'components', 'icons.svg.generated.ts'),
  header('The markup. For the static export — never imported by src/index.ts.') +
    `import type { IconId } from './icons.generated.ts';\n\n` +
    `export const ICON_SVG: Record<IconId, string> = {\n` +
    ICONS.map((i) => `  ${JSON.stringify(i.identifier)}: ${JSON.stringify(readFileSync(join(OUT, dirname(i.svg), `${i.identifier}.svg`), 'utf8'))},`).join('\n') +
    `\n};\n`,
);


const WRITTEN: readonly (readonly [file: string, what: string])[] = [
  ['assets/icons/svgs/', `${CATEGORIES.join(', ')} from @typo3/icons@${version}, MIT`],
  ['assets/icons/sprites/', `${CATEGORIES.length} sprite(s), one request per category`],
  ['assets/icons/icons.json', 'the one list, naming what is here, its paths relative to itself'],
  ['src/components/icons.generated.ts', 'the identifiers, typed, for the bundle'],
  ['src/components/icons.svg.generated.ts', 'the markup, for the static export'],
];
report.open('icons', 'regenerate assets/icons/ from @typo3/icons');
report.align(WRITTEN.map(([file]) => ({ name: file, label: file })));
for (const [file, what] of WRITTEN) report.fact(file, what);
report.summary(`${ICONS.length} icons \u00b7 ${CATEGORIES.length} categories`);
