#!/usr/bin/env node
/* Materialise assets/icons/ from the @typo3/icons package.

   The icons are TYPO3's own, and the identifiers below are the core's own —
   the same strings `typo3_icon_lookup` returns — so design and runtime name
   the same thing. Pulling them from the package instead of committing copies
   means npm owns the version and drift is impossible.

   A missing icon is contributed upstream, never drawn locally and never
   substituted from another set. So this script FAILS if a declared
   identifier does not exist in the package: that is the rule enforcing
   itself, not an inconvenience to work around.

   Run by the container entrypoint whenever the icons are missing, so any
   container starts with a working tree.

     make icons
*/
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { ROOT } from './lib/cards.ts';

/* The 33 icons this design system uses. Adding one here is the only step
   needed to ship it; if it is not upstream yet, contribute it there first. */
const ICONS = [
  'actions-arrow-right', 'actions-book', 'actions-check', 'actions-check-circle',
  'actions-chevron-down', 'actions-chevron-end', 'actions-chevron-start', 'actions-chevron-up',
  'actions-clock', 'actions-close', 'actions-code', 'actions-code-commit',
  'actions-code-compare', 'actions-code-pull-request', 'actions-cog', 'actions-database',
  'actions-debug', 'actions-duplicate', 'actions-exclamation-circle',
  'actions-exclamation-triangle', 'actions-extension', 'actions-filter', 'actions-history',
  'actions-info-circle', 'actions-link', 'actions-list', 'actions-menu-alternative',
  'actions-play', 'actions-question-circle', 'actions-refresh', 'actions-search',
  'actions-tag', 'actions-window-open',
];

const PKG = join(ROOT, 'node_modules', '@typo3', 'icons');
const OUT = join(ROOT, 'assets', 'icons');

/* `src/` rather than `dist/svgs/`: dist is SVGO-optimised, and these files
   are read by people deciding what to inline. The rendered result is the
   same either way. */
/** `actions-search` lives at `src/actions/actions-search.svg` — the
    identifier's first segment is its category. */
const categoryOf = (id: string): string => id.split('-')[0] ?? id;

const missing = ICONS.filter((id) => !existsSync(join(PKG, 'src', categoryOf(id), `${id}.svg`)));
if (missing.length) {
  console.error(`✗ not in @typo3/icons: ${missing.join(', ')}`);
  console.error('  Contribute the icon to TYPO3/TYPO3.Icons — do not draw it locally.');
  process.exit(1);
}

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
for (const id of ICONS) {
  copyFileSync(join(PKG, 'src', categoryOf(id), `${id}.svg`), join(OUT, `${id}.svg`));
}
copyFileSync(join(PKG, 'LICENSE'), join(OUT, 'LICENSE-TYPO3.Icons.txt'));

const version = JSON.parse(readFileSync(join(PKG, 'package.json'), 'utf8')).version;

/* The same 33 icons as one TypeScript module, so a component can inline an
   icon in the browser and the card generator can inline the identical string
   in Node. Reading assets/icons/*.svg directly works only in Node; a Vite
   import of the directory works only in the browser. This file is the one
   artefact both sides can import, which is why it is generated here rather
   than written by hand — a copy would be free to drift from the SVGs above.

   It is emitted as `.ts` for the `IconId` union: with it, `icon('actions-ply')`
   is a compile error naming the 33 valid identifiers, instead of a throw at
   render time that only shows up once someone opens that card. The union is
   generated from the same list, so it cannot fall behind it.

   Raw package source, untouched: the transformation into an inline
   `<svg class="sds-icon">` belongs to src/components/icon.ts, shared by both sides
   too. */
writeFileSync(
  join(ROOT, 'src', 'lib', 'icons.generated.ts'),
  `/* GENERATED by scripts/icons.ts — @typo3/icons@${version}, MIT. Do not edit.\n` +
    `   Add an identifier to the ICONS list in that script and run \`make icons\`. */\n\n` +
    `export type IconId =\n${ICONS.map((id) => `  | '${id}'`).join('\n')};\n\n` +
    `export const ICON_SVG: Record<IconId, string> = {\n` +
    ICONS.map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(readFileSync(join(OUT, `${id}.svg`), 'utf8'))},`).join('\n') +
    `\n};\n`,
);

console.log(`assets/icons/ — ${ICONS.length} icons from @typo3/icons@${version}, MIT`);
console.log(`src/lib/icons.generated.ts — the same ${ICONS.length}, typed, importable from Node and the browser`);
