#!/usr/bin/env node
/* Materialise assets/icons/ from the @typo3/icons package.

   The icons are TYPO3's own, and the identifiers below are the core's own —
   the same strings `typo3_icon_lookup` returns — so design and runtime name
   the same thing. Pulling them from the package instead of committing copies
   means npm owns the version and drift is impossible.

   A missing icon is contributed upstream, never drawn locally and never
   substituted from another set. So this script FAILS if a declared
   identifier does not exist in the package: that is the rule enforcing
   itself, not an inconvenience to work around.

   Run by the container entrypoint whenever the icons are missing, so any
   container starts with a working tree.

     make icons
*/
import { copyFileSync, cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { ROOT } from './lib/cards.ts';

/* Which categories this system ships. Everything else about an icon —
   whether it exists, where its file is, which sprite carries it, what a
   deprecated spelling resolves to — comes from the package's own manifest.
   Nothing here scans a directory or guesses a path from an identifier. */
const CATEGORIES = ['actions'] as const;

const PKG = join(ROOT, 'node_modules', '@typo3', 'icons');
const OUT = join(ROOT, 'assets', 'icons');

interface Manifest {
  icons: Record<string, { identifier: string; category: string; svg: string; sprite: string }>;
  aliases: Record<string, string>;
}

const manifest = JSON.parse(readFileSync(join(PKG, 'dist', 'icons.json'), 'utf8')) as Manifest;
const ICONS = Object.values(manifest.icons)
  .filter((i) => (CATEGORIES as readonly string[]).includes(i.category))
  .sort((a, b) => a.identifier.localeCompare(b.identifier));

const missing = ICONS.filter((i) => !existsSync(join(PKG, 'dist', i.svg)));
if (missing.length) {
  console.error(`✗ named by the manifest but not on disk: ${missing.map((i) => i.identifier).join(', ')}`);
  process.exit(1);
}

rmSync(OUT, { recursive: true, force: true });

/* The package's own layout, mirrored.

   Three shapes, none of them rebuilt here: a single file is what a Twig
   `source()` or a build step reaches for, the sprite is one request for a
   whole category, and the manifest is the lookup — which identifier exists,
   which category it belongs to, what a deprecated spelling resolves to.

   The manifest's paths are relative to itself (`svgs/actions/x.svg`), so the
   files have to sit where it says they do. Flattening them and keeping the
   manifest verbatim would ship a lookup that resolves to nothing. */
mkdirSync(join(OUT, 'svgs'), { recursive: true });
mkdirSync(join(OUT, 'sprites'), { recursive: true });
for (const category of CATEGORIES) {
  cpSync(join(PKG, 'dist', 'svgs', category), join(OUT, 'svgs', category), { recursive: true });
  copyFileSync(join(PKG, 'dist', 'sprites', `${category}.svg`), join(OUT, 'sprites', `${category}.svg`));
}

/* Filtered to what is actually here. Copied verbatim it would name 404 icons
   this system does not ship — the same shape of lie as a stale token. */
const shipped = new Set(ICONS.map((i) => i.identifier));
writeFileSync(join(OUT, 'icons.json'), `${JSON.stringify({
  icons: Object.fromEntries(ICONS.map((i) => [i.identifier, i])),
  aliases: Object.fromEntries(Object.entries(manifest.aliases).filter(([, to]) => shipped.has(to))),
}, null, 0)}\n`);

copyFileSync(join(PKG, 'LICENSE'), join(OUT, 'LICENSE-TYPO3.Icons.txt'));

const version = JSON.parse(readFileSync(join(PKG, 'package.json'), 'utf8')).version;

/* Two generated modules, split by who may pay for them.

   Both sit beside `icon.ts`, because they are the icon component's and
   nothing else's. `icons.generated.ts` is the identifiers and their type. It is small, and
   the browser bundle imports it: `IconId` makes `icon('actions-ply')` a
   compile error naming every valid identifier instead of a throw at render
   time, and the icons specimen needs the list.

   `icons.svg.generated.ts` is the markup, and it is the expensive one — every
   glyph as a string. Only `icon.static.ts` imports it, and only Node reaches that. In a browser the sprite does this job, so this
   file must never reach the bundle; splitting it out is what keeps that true
   by construction rather than by discipline.

   Raw package source, untouched: turning it into an inline `<svg>` belongs to
   the render path. */
const header = (what: string): string =>
  `/* GENERATED by scripts/icons.ts — @typo3/icons@${version}, MIT. Do not edit.\n` +
  `   ${what}\n` +
  `   Add a category to CATEGORIES in that script and run \`make icons\`. */\n\n`;

writeFileSync(
  join(ROOT, 'src', 'components', 'icons.generated.ts'),
  header('The identifiers. Safe for the browser bundle.') +
    `export type IconId =\n${ICONS.map((i) => `  | '${i.identifier}'`).join('\n')};\n\n` +
    `export const ICON_IDS: readonly IconId[] = [\n` +
    ICONS.map((i) => `  ${JSON.stringify(i.identifier)},`).join('\n') +
    `\n];\n`,
);

writeFileSync(
  join(ROOT, 'src', 'components', 'icons.svg.generated.ts'),
  header('The markup. For the static export — never imported by src/index.ts.') +
    `import type { IconId } from './icons.generated.ts';\n\n` +
    `export const ICON_SVG: Record<IconId, string> = {\n` +
    ICONS.map((i) => `  ${JSON.stringify(i.identifier)}: ${JSON.stringify(readFileSync(join(OUT, dirname(i.svg), `${i.identifier}.svg`), 'utf8'))},`).join('\n') +
    `\n};\n`,
);


console.log(`assets/icons/svgs/ — ${CATEGORIES.join(', ')} from @typo3/icons@${version}, MIT`);
console.log(`assets/icons/sprites/ — ${CATEGORIES.length} sprite(s), one request per category`);
console.log(`assets/icons/icons.json — the lookup, its paths relative to itself`);
console.log(`src/components/icons.generated.ts — the identifiers, typed, for the bundle`);
console.log(`src/components/icons.svg.generated.ts — the markup, for the static export`);
